[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Netlify Functions for Next.js
[functions]
  external_node_modules = ["next"]
  node_bundler = "esbuild"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Lighthouse plugin for performance monitoring
[[plugins]]
  package = "netlify-plugin-lighthouse"
  
  [plugins.inputs]
    # URLs to audit (relative to your site)
    audits = [
      "/",
      "/products", 
      "/blog",
      "/contact",
      "/projects"
    ]
    
    # Lighthouse settings
    settings = { onlyCategories = ["performance", "accessibility", "best-practices", "seo"] }
    
    # Upload results to Netlify deploy
    uploadResults = true
    
    # Set performance budget thresholds
    budgetPath = "./lighthouse-budget.json"
    
    # Run audit only on production builds
    skipAuditsOnBranches = ["preview", "branch-deploy"]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; media-src 'self'; object-src 'none'; child-src 'none'; worker-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'; manifest-src 'self';"

# Cache optimization
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

